### ISSUE TITLE
Add context on availability

### ISSUE THREAD

**Issue by livgust** [livgust/macovidvaccines.com#7] opened 2021-02-12 19:32 UTC
Provide some kind of UI element that is able to provide the following feedback (this is not official copy or anything):

- Sometimes we show availability but no sign-up link. This is because the state website doesn't give us a sign-up link. Why? Don't know.
- Sometimes we show a sign up link but no specific availability (right now there's a message saying "No date-specific data available." This is because we are able to determine that there are available appointments, but we can't tell you when or how many.

**Comment by harcod** [comment] 2021-02-14 19:01
> Sometimes we show availability but no sign-up link. This is because the state website doesn't give us a sign-up link. Why? Don't know.

I was on a conference call last week with officials (mostly politicians) about the registration on MAImmunizations.org

Once all of the appointments are filled, the site collects some number of "stand-by" people that can be called up when slots open up, then it removes the Sign-up link.  When people that have confirmed appointments cancel their appointment, their site shows that as an available dose.  They internally use this information to contact someone on the "stand-by list" to fill it.

**Comment by Kathleen-Francis** [comment] 2021-02-14 20:07
I think it would be helpful to have a separate "About" page with this kind of context, FAQ, etc, instead of just the dialog box. It's been a couple years since I've worked with React, but I think it would be pretty simple to add routing and an additional page like that. I've used [React Router](https://reactrouter.com/web/guides/quick-start) before, but looks like [Reach Router](https://reach.tech/router/) might be simpler?

In addition, when the `No date-specific data available.` message is shown, it could have a `?` icon or something that you could click and get a little dialog with additional context.

**Comment by Kathleen-Francis** [comment] 2021-02-16 00:45
Discussed in [slack](https://macovidvaccines.slack.com/archives/C01NBP1N1G9/p1613399739146900?thread_ts=1613396392.143800&cid=C01NBP1N1G9) and decided to start with adding the help icon/dialog box.

I'm starting to work on this, but can't assign to myself bc I'm not a collaborator.

**Closed** 2021-02-17 21:01 UTC
Labels: enhancement
